[licenses]
allow = ["MIT", "BSL-1.0", "Zlib"]
exceptions = [
    # FIXME: Shouldn't allow these?
    { name = "sha1", allow = ["BSD-3-Clause"] },
    { name = "subtle", allow = ["BSD-3-Clause"] },
]


[bans]
multiple-versions = "warn"
skip-tree = [
    # waiting for next `cookie` release to resolve the subtle v1.0.0/v2.2.3 duplication.
    { name = "cookie", version = "=0.14.1" },
]
